---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./calibre/ks.yaml
  - ./esphome/ks.yaml
  - ./home-assistant/ks.yaml
  - ./home-assistant-matter-hub/ks.yaml
  - ./immich/ks.yaml
  - ./jellyfin/ks.yaml
  - ./mealie/ks.yaml
  - ./unifi/ks.yaml
  - ./wallos/ks.yaml
  - ./zwave-js-ui/ks.yaml
