apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-settings
    namespace: flux-system
data:
    TIMEZONE: ENC[AES256_GCM,data:fOulPO4l625UyXSqtNlVFw==,iv:ZM91fbm5/8yj4xh/+H4qt3aSecn/wjNidqlVcPxDWZU=,tag:iVQ133i99mrde+LKHUEOSw==,type:str]
    CLUSTER_CIDR: ENC[AES256_GCM,data:Wz2sfvvyPXRdB9BM,iv:YrAnOq1uPkWKTzOvO6rVZMn8gBEB0dlpwZzoCV/J1Nc=,tag:k2KtBars0DuyoWl2d0N1eQ==,type:str]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:ZbtqlDuP62du,iv:PEm/r7ZlEUs4InW7vS3uW9e1NUYfhI3gh83Vfjm5k24=,tag:u8SpmFbp32w1/7ge2ntkzg==,type:str]
    #ENC[AES256_GCM,data:fmWOQ+XUxRsnAPj2TjHG4R+R1g==,iv:2FxAFxqfnPGLTvJ42rfsW9Dbqgza1oYdT0+hdRzVT2o=,tag:6sNX7VZ7EENS496Zh88sQQ==,type:comment]
    CLUSTER_CIDR_V6: ENC[AES256_GCM,data:NR4wnXYRBIs6CQeIsFjsVeUprU1ci72zSgQ=,iv:KAwCn6ZS4H85Ro9ueXOCkYXEkY+SjlUDomFk2AVTVz8=,tag:x6ydMLdT6pJwla5XSiOa+w==,type:str]
    NODE_CIDR: ENC[AES256_GCM,data:4gNOQPqBafS0n+HI+BwLrQ==,iv:tM9P6nsw8XLS4/tt7qj1p/de/05iaRpWWh+tssUEwpo=,tag:6FQL67XKyj4djz2zZL9c1w==,type:str]
    SERVICE_CIDR: ENC[AES256_GCM,data:qYTub9t5NUWz9L5q,iv:Rm57lhxjcqQVlvBdPXKXYGIu0ai3GPxbtE+HdXMxOOY=,tag:GbZ0jmmp/9uxCUiIjnPS7Q==,type:str]
    SERVICE_CIDR_V6: ENC[AES256_GCM,data:CON/94nJ5z47YyMeaPKRMM50L1D5+Iu8cWpA,iv:jmWPpkLZpvhe1BiXNkmHfwJj1Kg2PtTnm9lRD9LLVsY=,tag:EIrWfjzeoCrjcq3UTgwNdQ==,type:str]
    #ENC[AES256_GCM,data:RHxJSqVsIS7bo9yk3blyPwQHCebXQFvb,iv:rF3i58Cw5Js3f4xDOFpsWGviJxHuDhY3PEarAGZ5JfI=,tag:IwQ+F3L3zhOSuulxVajjWw==,type:comment]
    DNS_CIDR_V4: ENC[AES256_GCM,data:2s+uxJMzcbfk4qr/xH8=,iv:bhOW3thpcHAGs5Fi5rCe90ITGh7jteM3ak1RvAXxRLk=,tag:/+kBrzELI/DwTd0JWkjkuA==,type:str]
    GATEWAY_CIDR_V4: ENC[AES256_GCM,data:bMHOIJ7IIsamgTaJldM=,iv:fTC5pxHVgLSQND+9u3ZAyInGQJJuoKuHNXhtivMVQn4=,tag:HEhvay8Yc4a5YQC5dw/nOA==,type:str]
    INTERNAL_PROXY_CIDR_V4: ENC[AES256_GCM,data:j/6Fn7d0Z2MaGF+pfWc=,iv:mZ1342vWoshhgyPgFribQwYiQ26gM1rR5gujCh7OO1o=,tag:0bu6WxRQSLGWGJ1dGwcTbA==,type:str]
    EXTERNAL_PROXY_CIDR_V4: ENC[AES256_GCM,data:tCF7hmDb+HmWn1Y3zuw=,iv:7jTzbV5NPrH8nmDIQ8Rrnt+zoLow2+IftOf7yWCyVJY=,tag:S5TEk9OfKuZ7fvxZtzXSPA==,type:str]
    LB_UNIFI_CIDR_V4: ENC[AES256_GCM,data:80Q9CCzmLrJ+UbrKCEQ=,iv:kkl+S2k1clI9Rec6e7XMyA2kHyhtsRBFZithlmC+B5c=,tag:YvoVCzOBhr58fWRuxrgu9w==,type:str]
    CLUSTER_LB_MINECRAFT_ROUTER_V4: ENC[AES256_GCM,data:+BiieKJ0jFSd5SwCf1M=,iv:mnp1jAwUcb/+ZcHk8bKn/6pPT43CDBTRF1to+bVdOhc=,tag:j1JMc87x11fF7wJLKWq4bQ==,type:str]
    LB_EMQX_CIDR_V4: ENC[AES256_GCM,data:irDsQFzPJMlB8nq4eds=,iv:trTp/3EDJoYKlceLrshGejMT8ZORK52C5ALNV0E4L0U=,tag:U8/EetK/oyTJWguijnBBxg==,type:str]
    LB_CIDR_MINECRAFT_V4: ENC[AES256_GCM,data:HCDYBxNJIcGKfFRCh80=,iv:58AuCOh2bP6uCCzm5H5SshgAWBU3V1giaSJYGmK/e9k=,tag:dhsHmLGmeXGOeOKqKGVekg==,type:str]
    LB_CIDR_GEYSERMC_V4: ENC[AES256_GCM,data:x8ZtunMawwYHMdIjD14=,iv:eDzLFWhvCgOzDctntIYPIizeVDV//Fej7a6r91J5K5U=,tag:cvBzd3H31DLUtHYaAEDU0g==,type:str]
    #ENC[AES256_GCM,data:p5At/oRwAxScqW1Wb+A9ztqikxMdCqII5cSd3GGJMN6MarHIWw2bnGvMd0uY,iv:N61y9DjTmUJ0PXLRjcezB/FnJDAbQMTcyhT5rqGh1No=,tag:1aBuFHxPbuGkcCwAqn9T3g==,type:comment]
    LB_CIDR_V4: ENC[AES256_GCM,data:hcsxz6rvBcIp0m61/cAcS+c=,iv:9PZ9F3pG2p0S/v8pxOini1XB3GUUSxRzXcPu0eheaOU=,tag:ztKilCWofjW5yJe7u0RiFA==,type:str]
    LB_CIDR_V6: ENC[AES256_GCM,data:mFeFmr1SyqcqQQAXlW2zHgQOe5ooMsgCKqOBDhm2,iv:iAzCogIclTsWIH92dLPJtywVzOYu6wDNebAwG7oHbLA=,tag:WV5u9VShFSktCwCWG4jIUw==,type:str]
    #ENC[AES256_GCM,data:EeMZz6R5zmlG3eBfGqbr,iv:KWgEeRh1zRFnRTU2Im+7lNluqlsZAxBaKXG/oHYDdAc=,tag:7FrWbI5RZR4EzVviCHm2ag==,type:comment]
    BITWARDEN_APP_ID: ENC[AES256_GCM,data:GVMHGdgeyHoHs1VJANFNSeR0sp78b3xKqsrDXhrE3PYdVqr6OClTFrESNEhOoRqEIw==,iv:iSm8K9FhHupPyOkLbs+aXuI91RwlXHvfWeujwJbeWOk=,tag:MLXwK3jBlP+4NYs/e+nrZg==,type:str]
    NFS_SUBDIR_PATH: ENC[AES256_GCM,data:aeYYqtdZPOMPRRoKmGKa6k99occFacR+kEa6qocHEOWQrkgmw+DmDhv3nP1H2+pUmKyBGZCHlYgihUELt3jlFhlWY3iM,iv:FgO48pc19BdiVz38nFrgUl1LIrY4vVrtPEgL90gwllE=,tag:byc+QtIcBR/6ppDuXqzOuw==,type:str]
    PIHOLE_ADDR: ENC[AES256_GCM,data:ZywNFkXzx5U7hqhH95N9,iv:TTvrDXS6TIdh3LZOq0mcPjN56my+eBmC0plPtTpJyqM=,tag:NLjbIDyaR/s9szqxoqROGg==,type:str]
    ZWAVE_NODE: ENC[AES256_GCM,data:oz69XEXG4cUf7jvK0aM=,iv:25Yucvyj7YAUx9/xL7JFHK2CvqHoO6PxkaZQMtV8gTs=,tag:x3d4hKTF4PkofZIuhMZLIg==,type:str]
    ROUTER_CIDR_V4: ENC[AES256_GCM,data:MRQfLr5czCksXUCT9g==,iv:3leOotkYCMd3VkfGPI4GcdBqyVyc1PoueiixGNOAp+s=,tag:NVgeqZI2ZV5n1QbaBHaxZA==,type:str]
    #ENC[AES256_GCM,data:omVHcwU3zr7g1L28gjG1nDqOttkIlK9iV2A=,iv:QT2WUMDRXtKzkoOEPmNtqM5UYxfw9xy6hM7/UN+MdBA=,tag:3Eyewohh2Rz+SJaHWX53Aw==,type:comment]
    CONTROLLER_IP_1: ENC[AES256_GCM,data:zvhYJsFoW0K0JvcLAbA=,iv:ED4M0AeLayPASzzkvOY9o/rwhpd7KVIqcSaWNVsB21g=,tag:Ggoylrx/Oaz6e3qNHfK4yA==,type:str]
    CONTROLLER_IP_2: ENC[AES256_GCM,data:Rpuvoa2DWvOEl9IEakA=,iv:goJDOrZDrPNCFO1BFHkEEvyGZwivRnMYdPidQOqs6Y0=,tag:2F+l0zHFzGjuv6WOCiu6TQ==,type:str]
    CONTROLLER_IP_3: ENC[AES256_GCM,data:koCNPV8oyIm3f9NnwNU=,iv:/PjRL+gHh0nGc5nPfOlplUmUo+3TFad2QvIwdt0U8uQ=,tag:6HRsUc68UIYzG/q36hQ5hA==,type:str]
    #ENC[AES256_GCM,data:g6tP7PtafP+mBqIS69U+Rw==,iv:yBfpvI0ECx4BB0OlYOfwN66uxud7YUAlitZCoLp3Rbo=,tag:Hf43i+ZhMRAQPmOaoaa/1Q==,type:comment]
    IOT_CIDR: ENC[AES256_GCM,data:6bi+558s6hdmPQi0/b0=,iv:r8FHGvWVQKIs/tef3X1fKkq2oLS2D9yx6NqFOxuMKP8=,tag:Q5ZRTX/yT9I8LlPiPrvYMA==,type:str]
    IOT_GATEWAY: ENC[AES256_GCM,data:lGPyVaPz+qyvAWU=,iv:EwnpOsRyoMKaXMGCREQS4LfQVchFHZVXeyTYG1D4oOs=,tag:4H2ynoO6o3MwPYd1J89Tew==,type:str]
    LAN_CIDR: ENC[AES256_GCM,data:HRt8r9PBjhKCZrEm7E56Fw==,iv:5bCLUwBH94leR1N9z8W8M2Rp8ebtEJx6hfYY55g39BA=,tag:VZYtEdZbsqXgL13AFRt33g==,type:str]
    LAN_GATEWAY: ENC[AES256_GCM,data:8BSeAkEnxRUNJP65hA==,iv:jtXZBG+Dl7VXpq3/PTLcoRWHjBWkNBkNfyHdGBF3MrI=,tag:iLe69ewe73T63i8bOZdXUg==,type:str]
    DNS_SUFFIX: ENC[AES256_GCM,data:bUEeIC1urF0f,iv:TUuVvTdKSBA2USg5Pqq77AWyi20OGA7YJe/Yv0hSCQ8=,tag:Yl4K6EhcCSimrfDxFV7ZvQ==,type:str]
    MATTER_HUB_IOT_CIDR_V4: ENC[AES256_GCM,data:3xkPrgWuEWVIj+HjGEnS,iv:PhaHEbk8SBHfedbNoTa3wpeaI3TvLzP0K8EfqDyA/hM=,tag:Q457cLrDhb0nvVeIKkBEOQ==,type:str]
    HOME_ASSISTANT_IOT_CIDR_V4: ENC[AES256_GCM,data:rgEZsOemzO5l2HQ3uOPB,iv:R/YS06Ls9qHoh4rXtPV9cD53sI3tNRM18GP8KiaHTvI=,tag:xo0I6lYBIJNZVHYr4BMk+g==,type:str]
    #ENC[AES256_GCM,data:obsJRA==,iv:IPMrd9ZUCXpOYx7jb3FuN6DxP7ZhzjIaKFwyDWNH5vI=,tag:nH5ufgbAtbkFD0+RSAnhvA==,type:comment]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:MuVW/eCJ,iv:/f7oaTIEAlMue2SNV/kFZ2ADB4/rU0yIp1Fe1wqkUWk=,tag:D2swvpjN/tHyoGdNSPOiUw==,type:str]
    VPN_SERVER_COUNTRIES: ENC[AES256_GCM,data:zYiw/y7uIaTesyI=,iv:xzCt3WNITnPZtYnFaUzIJKWdIxubLIY6Cy/TBH0RMOg=,tag:5hBIA2O/kV0YF1+pEUojuw==,type:str]
    VPN_COUNTRY_CODE: ENC[AES256_GCM,data:bLk=,iv:jup7y2m4nkHyp/FncxqZr2NaqsnpLxbkFYyX0ugQu5k=,tag:XX2vNupYa7UDI9PRAx7wUg==,type:str]
    VPN_FORWARDED_PORT: ENC[AES256_GCM,data:WV2oolA=,iv:kzXN1ILTCya6jNoVtqiWT0TSuN+1koqqKOUGAAV9b/c=,tag:bAvrlcrruOMOQMhPVbCDoQ==,type:str]
sops:
    age:
        - recipient: age1sy27zexxvef2q63aeky2uuhmm0rvrclqf6fzfu2qqe2pc0w6rc8s7fde68
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OFVDSzRTVU5SVnNua1dO
            UXREb1drQkpkQWI4Sk1BUExhTnFQVTczMW04Clh6L2pDNzFQZmJLdlljVngwb2w4
            cVlEU1dsZXVhcVg0czI0MnliWjBuOVEKLS0tIDdjMVBnODVKdEZHZE5ZSFpCZHhm
            K1hwQXViSGo2Vlc4aWlhcVNlODN0YjAKEILj46nOoqdd8/LwuNqksNNmVEPYeTUb
            z7YvduznYuJFFcNQ54jQej8ZqXX42HNfGtWX4B3K5OjXptTklAnfEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T16:21:18Z"
    mac: ENC[AES256_GCM,data:VwTZfq7RP04LJsyAfRLg1LyfAsXSFC/rtwZ1ER1Fmo38Y0W9zBEM9furkx+Q1QC7QE7iBei9kcTPnOURwIsjWCdOzD+fgpI6VNSXVUg36HGH6DtTvwRpXryi3SEUXSoMfBNZhFB3HPUzunuaGfuaCtjFnLSw8hlM2NTbyg4rtME=,iv:v80AM19g1j8W9jZLel4ux7WM7fCkly/l6D+I5F0xfHk=,tag:KD/CIXwcKAwClWHkdQQEag==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
